benches: Use std::hint::black_box instead of deprecated criterion::black_box
```
error: use of deprecated function `criterion::black_box`: use `std::hint::black_box()` instead
 --> benches/fk.rs:1:17
  |
1 | use criterion::{black_box, criterion_group, criterion_main, Criterion};
  |                 ^^^^^^^^^
  |
  = note: `-D deprecated` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(deprecated)]`

error: use of deprecated function `criterion::black_box`: use `std::hint::black_box()` instead
   --> benches/fk.rs:144:13
    |
144 |             black_box(chain.joint_positions());
    |             ^^^^^^^^^

error: use of deprecated function `criterion::black_box`: use `std::hint::black_box()` instead
   --> benches/fk.rs:184:25
    |
184 |                         black_box(chain.joint_positions());
    |                         ^^^^^^^^^

error: use of deprecated function `criterion::black_box`: use `std::hint::black_box()` instead
   --> benches/fk.rs:209:25
    |
209 |                         black_box(chain.joint_positions());
    |                         ^^^^^^^^^
```